---
- name: generate account key
  openssl_privatekey:
    path: "{{ account_private_key }}"
    owner: "{{ rocket_chat_nginx_process_user }}"
    mode: 0600
    force: no

- name: generate csr key
  openssl_privatekey:
    path: "{{ rocket_chat_ssl_key_path }}"
    owner: "{{ rocket_chat_nginx_process_user }}"
    mode: 0600
    force: no

- name: create openssl csr
  openssl_csr:
    path: "{{ rocket_chat_letsencrypt_csr }}"
    privatekey_path: "{{ rocket_chat_ssl_key_path }}"
    common_name: "{{ rocket_chat_letsencrypt_domain | default(rocket_chat_service_host) }}"
    owner: "{{ rocket_chat_nginx_process_user }}"
    mode: 0600
    force: no

- name: create challenge for {{ rocket_chat_letsencrypt_domain | default(rocket_chat_service_host) }} using an account key from a variable
  letsencrypt:
    account_key_content: "{{ account_private_key }}"
    csr: "{{ rocket_chat_letsencrypt_csr }}"
    dest: "{{ rocket_chat_ssl_cert_file }}"
    acme_directory: https://acme-v02.api.letsencrypt.org/directory
    acme_version: 2
    challenge: tls-sni-02
  register: server_challenge

- name: perform the necessary steps to fulfill the challenge
  copy:
    dest: /var/www/html/{{ server_challenge['challenge_data']['{{ rocket_chat_letsencrypt_domain | default(rocket_chat_service_host) }}']['tls-sni-02']['resource'] }}
    content: "{{ server_challenge['challenge_data']['{{ rocket_chat_letsencrypt_domain | default(rocket_chat_service_host) }}']['tls-sni-02']['resource_value'] }}"
  when: server_challenge is changed

- name: Let the challenge be validated and retrieve the cert
  letsencrypt:
    account_key_content: "{{ account_private_key }}"
    csr: "{{ rocket_chat_letsencrypt_csr }}"
    dest: "{{ rocket_chat_ssl_cert_file }}"
    #fullchain_dest: /etc/httpd/ssl/sample.com-fullchain.crt
    #chain_dest: /etc/httpd/ssl/sample.com-intermediate.crt
    data: "{{ server_challenge }}"
    acme_directory: https://acme-v02.api.letsencrypt.org/directory
    acme_version: 2
    challenge: tls-sni-02
  notify: Reload the Nginx service
...
